In [ ]:
#Name:Lanke Payal Sambhaji
#Roll No:152
#Div:TY B
#FDSL MIDTERM
#Title:Assignment based on Numpy arrays and functions (Numpy Library)


In [122]:
#NumpyLibrary Import
import numpy as np #For Working with arrays and numerical operations


In [123]:
print(np.__version__)#Checking Numpy Version


2.3.1


In [124]:
#1D Array Creation
print("1D Array Creation")
arr=np.array([1,2,3,4,5],dtype=np.int32) #Array
print(arr)


1D Array Creation
[1 2 3 4 5]


In [125]:
#1D Array Properties
print("Array Dimension:",arr.ndim) #No of dimensions
print("Array shape:",arr.shape) #Shape of array
print("Array Size:",arr.size) #Size of array
print("Array Datatype",arr.dtype) #Data type of array 
print("First Element:",arr[0]) #Accessing first element of array
print(arr[-2]) #Reverse indexing or accessing second last element



Array Dimension: 1
Array shape: (5,)
Array Size: 5
Array Datatype int32
First Element: 1
4


In [126]:
#linspace function
import numpy as np
print(np.linspace(1, 20, num=5)) #5 values in between range 1 to 20 evenly spaced


[ 1.    5.75 10.5  15.25 20.  ]


In [127]:
#2D Array creation
arr1=np.array([[10,20,30],[40,50,60]]) # 2D array
print("2D Array",arr1) #Array
print("Dimension:",arr1.ndim) #Dimension of array
print("Shape:",arr1.shape) #Shape of array
print("Size:",arr1.size) #Size of array
print("Datatype:",arr1.dtype) #Datatype of array


2D Array [[10 20 30]
 [40 50 60]]
Dimension: 2
Shape: (2, 3)
Size: 6
Datatype: int64


In [128]:
#Zeros Array Creation
zeros_arr=np.zeros((2,3),dtype=np.float32) #2D array 
print("Zeros Array:",zeros_arr) #Array
print("Array Dimension:",zeros_arr.ndim) #no of dimension
print("Array shape:",zeros_arr.shape) #Shape of array
print("Array Size:",zeros_arr.size) #Size of array
print("Datatype:",zeros_arr.dtype) #datatype of array
print(zeros_arr[0,1]) #Accessing element at 0th row and 1st column



Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]]
Array Dimension: 2
Array shape: (2, 3)
Array Size: 6
Datatype: float32
0.0


In [129]:
#Ones Array Creation
ones_arr=np.ones((3,2),dtype=np.int32)
print("Ones Array:",arr3) #array

print("Array Dimension:",ones_arr.ndim) #no of dimension
print("Array shape:",ones_arr.shape) #Shape of array
print("Array Size:",ones_arr.size) #Size of array
print("Datatype:",ones_arr.dtype) #datatype of array
print(ones_arr[1,1]) #Accessing element at 1st row and 1st column



Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array Dimension: 2
Array shape: (3, 2)
Array Size: 6
Datatype: int32
1


In [130]:
#Array Reshaping
arr4=arr1.reshape((3,2)) #Reshaping 2D array to 3x2
print("New Reshaped Array:",arr4) #Array

print("Dimension:",arr4.ndim)
print("Shape:",arr4.shape)
print("size:",arr4.size)
print("Datatype:",arr4.dtype)
print(arr4[2,1]) #Accessing element at 2nd row and 1st column


New Reshaped Array: [[10 20]
 [30 40]
 [50 60]]
Dimension: 2
Shape: (3, 2)
size: 6
Datatype: int64
60


In [131]:
#Arrays
x=np.array([2,4,5,6])
y=np.array([1,2,3,4])
print(x)
print(y)

[2 4 5 6]
[1 2 3 4]


In [132]:
#Maximum element 
print("Maximum element:",arr1.max()) #max(large) element from arr1

Maximum element: 60


In [133]:
#Minimum element 
print("Minimum element:",arr1.min()) #min(small) element from arr1

Minimum element: 10


In [134]:
print(np.argmax(x)) #index of maximum element


3


In [135]:
print(np.argmin(x)) #index of minimum element


0


In [136]:
print(np.diff(x)) #Difference between adjacent elements of array


[2 1 1]


In [137]:
print(np.linspace(5,15,num=6)) #6 values in between range 5 o 15 evenly spaced

[ 5.  7.  9. 11. 13. 15.]


In [138]:
#Arithmetic Operations on array
print("Addition:",x+y) #addition
print("Subtraction:",x-y) #subtraction
print("Multiplication:",x*y) #multiplication
print("Division:",x/y) #division
print("Moduls:",x%y) #modulas


Addition: [ 3  6  8 10]
Subtraction: [1 2 2 2]
Multiplication: [ 2  8 15 24]
Division: [2.         2.         1.66666667 1.5       ]
Moduls: [0 0 2 2]


In [139]:
print("Square",x**2) #Square of each element in array x
print("Cube:",y**3) #cube of each element in array y

Square [ 4 16 25 36]
Cube: [ 1  8 27 64]


In [140]:
print("Square Root:",np.sqrt(x)) #Square root of each element 


Square Root: [1.41421356 2.         2.23606798 2.44948974]


In [141]:
#Mean of array
print("Mean of x:",np.mean(x))


Mean of x: 4.25


In [142]:
#Median of array
print("Median of y:",np.median(y))

Median of y: 2.5


In [143]:
#Array sum
print(np.sum(y)) #Sum of all elements in array y

10


In [144]:
print(np.swapaxes(arr1,0,1)) #Swapping axis of array

[[10 40]
 [20 50]
 [30 60]]


In [145]:
print(np.sort(arr1,axis=0)) #swapping array along axis 0
print(np.sort(arr1,axis=1)) #swapping array along axis 2

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]


In [146]:
zeros_arr.astype(np.int32) 


array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [147]:
?arr1 

Type:        ndarray
String form:
[[10 20 30]
 [40 50 60]]
Length:      2
File:        c:\users\hp\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype