In [1]:
import numpy as np
print(np.__version__)

2.3.1


In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print("Shape of the array:")
print(arr.shape)
print(arr.dtype)
print(np.swapaxes(arr,0,1))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of the array:
(4, 3)
int64
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [47]:
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
print(arr.max())

12


In [ ]:
import numpy as np
arrr=np.zeros((4,3),dtype=int)
print(arrr)
print(arrr.shape)
print(arrr.dtype)
print(arr.size)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
int64
12
<built-in method sum of numpy.ndarray object at 0x000001A7A69FE8B0>


In [68]:
ones_array=np.ones((3,4),dtype=int)
print(ones_array)



[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [59]:
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
zeros_array=np.zeros(5)
print(zeros_array)
print(type(zeros_array))
zeros_array.dtype
zeros_array.astype(np.int32)


[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
print(np.linspace(1,10,num=5))


[ 1.    3.25  5.5   7.75 10.  ]
int64
